version: "3.3"
services:
  postgres:
    container_name: forms-postgresql-db
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
  
  keycloak:
    container_name: forms-keycloak
    image: bitnami/keycloak:15
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_MANAGEMENT_USER=manager
      - KEYCLOAK_MANAGEMENT_PASSWORD=password
      - KEYCLOAK_DATABASE_HOST=postgres
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak_db
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_SCHEMA=keycloak_schema
      - KEYCLOAK_HTTP_PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local